modLoader="javafml"
loaderVersion="[37,)"
license="MIT"
issueTrackerURL="https://github.com/PaintNinja/SpammyCombat/issues"

[[mods]]
modId="spammycombat"
version="${file.jarVersion}"
displayName="SpammyCombat"
#updateJSONURL="https://change.me.example.invalid/updates.json"
displayURL="https://github.com/PaintNinja/SpammyCombat"
#logoFile="examplemod.png" # A file name (in the root of the mod JAR) containing a logo for display
authors="Paint_Ninja"
description='''
A mod that aims to restore the old click spamming combat from Minecraft 1.8 and older.
'''
[[dependencies.spammycombat]]
    modId="forge"
    mandatory=true
    versionRange="[37.1.1,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.spammycombat]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.17.1,1.18)" # This version range declares a minimum of the current minecraft version up to but not including the next major version
    ordering="NONE"
    side="BOTH"
