modLoader="javafml"
loaderVersion="[40,)"
license="MIT"
#issueTrackerURL="https://change.me.to.your.issue.tracker.example.invalid/"

[[mods]]
modId="spammycombat"
# The version number of the mod - there's a few well known ${} variables useable here or just hardcode it
# ${file.jarVersion} will substitute the value of the Implementation-Version as read from the mod's JAR file metadata
# see the associated build.gradle script for how to populate this completely automatically during a build
version="${file.jarVersion}"
displayName="SpammyCombat"
#updateJSONURL="https://change.me.example.invalid/updates.json"
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/"
#logoFile="examplemod.png" # A file name (in the root of the mod JAR) containing a logo for display
authors="Paint_Ninja"
description='''
A mod that aims to restore the old click spamming combat from Minecraft 1.8 and older.
'''
[[dependencies.spammycombat]]
    modId="forge"
    mandatory=true
    versionRange="[40.1.0,)"
    ordering="NONE"
    side="CLIENT"

[[dependencies.spammycombat]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)" # This version range declares a minimum of the current minecraft version up to but not including the next major version
    ordering="NONE"
    side="CLIENT"
